version: '3.7'

services:
  php:
    container_name: php
    build:
      context: ./api
    image: default_php
    depends_on:
      - db
    restart: always
    volumes:
      - ./api:/srv/api:rw
      - ./docker/php/conf.d/custom.dev.ini:/usr/local/etc/php/conf.d/custom.ini

  proxy:
    container_name: proxy
    image: nginx:alpine
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:rw
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/api.dev.conf:/etc/nginx/conf.d/api.conf
    ports:
      - "8080:8080"

  db:
    container_name: db
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
    restart: always
    expose:
      - "5432"
